### ISSUE TITLE
Position Left has some bugs

### ISSUE THREAD

**Issue by MidSpike** [fightforthefuture/june11-widget#1]
Position Left has some bugs...

Currently The css for .minimized is;
```
body[data-position="left"] .minimized {
    right: auto;
    left: 2.5rem;
    text-align: left;
}
```

It Should be;
```
body[data-position="left"] .minimized {
    right: auto;
    left: 2.5rem;
    text-align: center;
}
```

Also the fullscreen "No thanks, I don't want to take action" button ignores the position option when closing and always closes to the right

**Comment by kenmickles** [comment]
Thanks @tylerr514!
